**Final Project: Deep Learning**

Group 13:
- Ayaa Asoba
- Pablo González Martín
- Xavier Bruneau

# Set up

## Imports

In [8]:
import os
import pandas as pd

In [21]:
%load_ext autoreload
%autoreload 2

import sys
sys.path.append('../src/')  # o la ruta donde están tus módulos

import modeling
import plots
import utils
%reload_ext autoreload

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

## Paths

In [10]:
path_project = os.path.abspath(os.path.join(os.getcwd(), '..'))
path_data = os.path.join(path_project, 'data', 'ETT-small')

## General config

# Data Analysis

## Data preparation: extraction and cleaning

Download dataset

In [11]:
df = pd.read_csv(os.path.join(path_data, 'ETTh1.csv'))

In [12]:
df.head(10)

                  date   HUFL   HULL   MUFL   MULL   LUFL   LULL         OT
0  2016-07-01 00:00:00  5.827  2.009  1.599  0.462  4.203  1.340  30.531000
1  2016-07-01 01:00:00  5.693  2.076  1.492  0.426  4.142  1.371  27.787001
2  2016-07-01 02:00:00  5.157  1.741  1.279  0.355  3.777  1.218  27.787001
3  2016-07-01 03:00:00  5.090  1.942  1.279  0.391  3.807  1.279  25.044001
4  2016-07-01 04:00:00  5.358  1.942  1.492  0.462  3.868  1.279  21.948000
5  2016-07-01 05:00:00  5.626  2.143  1.528  0.533  4.051  1.371  21.174000
6  2016-07-01 06:00:00  7.167  2.947  2.132  0.782  5.026  1.858  22.792000
7  2016-07-01 07:00:00  7.435  3.282  2.310  1.031  5.087  2.224  23.143999
8  2016-07-01 08:00:00  5.559  3.014  2.452  1.173  2.955  1.432  21.667000
9  2016-07-01 09:00:00  4.555  2.545  1.919  0.817  2.680  1.371  17.445999

Transform date column to index

In [13]:
df.index = df['date']
df.index = pd.to_datetime(df.index)
df=df.drop(columns=['date'])

Stablish hourly frecuency

In [14]:
df = df.asfreq('h')

Analyze data types of the columns

In [15]:
df.dtypes

HUFL    float64
HULL    float64
MUFL    float64
MULL    float64
LUFL    float64
LULL    float64
OT      float64
dtype: object

In [16]:
df.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 17420 entries, 2016-07-01 00:00:00 to 2018-06-26 19:00:00
Freq: h
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   HUFL    17420 non-null  float64
 1   HULL    17420 non-null  float64
 2   MUFL    17420 non-null  float64
 3   MULL    17420 non-null  float64
 4   LUFL    17420 non-null  float64
 5   LULL    17420 non-null  float64
 6   OT      17420 non-null  float64
dtypes: float64(7)
memory usage: 1.1 MB

In [17]:
df.describe()

,HUFL,HULL,MUFL,MULL,LUFL,LULL,OT
count,17420.000000,17420.000000,17420.000000,17420.000000,17420.000000,17420.000000,17420.000000
mean,7.375141,2.242242,4.300239,0.881568,3.066062,0.856932,13.324672
std,7.067744,2.042342,6.826978,1.809293,1.164506,0.599552,8.566946
min,-22.705999,-4.756000,-25.087999,-5.934000,-1.188000,-1.371000,-4.080000
25%,5.827000,0.737000,3.296000,-0.284000,2.315000,0.670000,6.964000
50%,8.774000,2.210000,5.970000,0.959000,2.833000,0.975000,11.396000
75%,11.788000,3.684000,8.635000,2.203000,3.625000,1.218000,18.079000
max,23.643999,10.114000,17.341000,7.747000,8.498000,3.046000,46.007000

Declare the dependent and the predictors columns

In [18]:
y = 'OT'
features = [col for col in df.columns if col != y]

## Descriptive analysis

Time series for the Oil Temperature (OT) variable

In [22]:
plots.plot_time_series(df.reset_index(), date_col="date", value_col=y, period="daily", title='Oil Temperature series over the 2016-2018 period')

![](../images/TimeSeriesOilTemperature.png)

Time series including the predictors

In [23]:
plots.plot_time_series_predictors(
    df,
    predictors=features+[y], # We observe the dependent variable too
    date_col="date",
    period="daily",
)

![](../images/TimeSeriesPredictors.png)

In [25]:
plots.plot_time_series_decomposition(df,y,title='Time Series Decomposition', period=24, model='additive')

NameError: name 'seasonal_decompose' is not defined

# Modeling

## Model A

This is Pablos Model

## Model B

## Model C

# Conclusions

## Model comparisons

## Final summary